name: Scheduled GitHub Actions Demo

on:
  schedule:
    # Run at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello from scheduled GitHub Actions workflow!"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Display scheduled run information
        run: |
          echo "===========================================" 
          echo "Running scheduled GitHub Actions workflow"
          echo "Current date: $(date)"
          echo "This job runs daily at midnight UTC"
          echo "===========================================" 
      
      - name: Display system information
        run: |
          echo "System Information:"
          echo "OS: $(uname -a)"
          echo "Current directory: $(pwd)"
          
      - name: Display environment variable
        run: echo "Greeting: $GREETING"
        
      - name: Read text file
        run: cat main.txt
          
      - name: Generate daily report
        run: |
          echo "Daily report generated on $(date)" > daily_report.txt
          echo "GitHub Actions scheduled workflow completed successfully" >> daily_report.txt
          echo "Greeting used: $GREETING" >> daily_report.txt
          echo "" >> daily_report.txt
          echo "Contents of main.txt:" >> daily_report.txt
          cat main.txt >> daily_report.txt
          cat daily_report.txt 